use QLBH
GO

DROP PROC IF EXISTS CAP_NHAT_TT_MONAN
GO
CREATE PROCEDURE CAP_NHAT_TT_MONAN
@tenmon nvarchar(80),
@matd int,
@tt NVARCHAR(30)
AS
	BEGIN TRAN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
		BEGIN TRY
			IF NOT EXISTS (SELECT *
						   FROM MONAN
						   WHERE TENMON = @tenmon)
			BEGIN
				RAISERROR('MON AN KKONG TON TAI',16,1)
				ROLLBACK TRAN
				RETURN
			END

			IF @tt = NULL
			BEGIN
				RAISERROR('TINH TRANG KHONG HOP LE',16,1)
				ROLLBACK TRAN
				RETURN
			END

		END TRY

		BEGIN CATCH
				RAISERROR('KHONG CAP NHAT DUOC',16,1)
				ROLLBACK TRAN
				RETURN
		END CATCH	
		
		BEGIN
			IF EXISTS (SELECT *
					   FROM MONAN 
					   WHERE TENMON = @tenmon AND MATHUCDON = @matd)
			 WAITFOR DELAY '00:00:05'
			 BEGIN
				UPDATE MONAN 
				SET TINHTRANGMON = @tt
				WHERE MATHUCDON = @matd AND TENMON = @tenmon
			END
		END

	COMMIT TRAN