--DIRTY READ: Khach Cap Nhat CTDH nhung thay doi lai, CuaHang doc CT_DH truoc luc thay doi
--DROP PROC CAP_NHAT_CT_DON_HANG
DROP PROC IF EXISTS CAP_NHAT_CT_DON_HANG
GO
CREATE PROCEDURE CAP_NHAT_CT_DON_HANG
@madh char(8),
@tm nvarchar(38),
@sl int,
@check int
AS
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT *
						   FROM CT_DONHANG
						   WHERE MADH = @madh AND TENMON = @tm)
			BEGIN
				RAISERROR('KHONG TON TAI DON HANG',16,1)
				ROLLBACK TRAN
				RETURN				
			END

			UPDATE CT_DONHANG
			SET SOLUONGMON = @sl
			WHERE MADH = @madh AND TENMON = @tm

			WAITFOR DELAY '00:00:05'

			IF @check = 1
				BEGIN
					ROLLBACK TRAN
					RETURN
				END
		END TRY
		
		BEGIN CATCH
			RAISERROR('KHONG THE CAP NHAT',16,1)
			ROLLBACK TRAN
			RETURN
		END CATCH
	COMMIT TRAN

GO

DROP PROC IF EXISTS DOC_CT_DH
GO
CREATE PROCEDURE DOC_CT_DH
@madh char(8),
@tm nvarchar(38)
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT *
						   FROM CT_DONHANG
						   WHERE MADH = @madh AND TENMON = @tm)
			BEGIN
				RAISERROR('KHONG TON TAI DON HANG',16,1)
				ROLLBACK TRAN				
			END
		END TRY

		BEGIN CATCH
			RAISERROR('KHONG THE COI',16,1)
			ROLLBACK TRAN
		END CATCH
			
		BEGIN
			 SELECT *
			 FROM CT_DONHANG
			 WHERE MADH = @madh AND TENMON = @tm
		END
		COMMIT TRAN