-- This file will be updated weekly by Group02

use QLBH
go

---- < Role: KHACHHANG > ----
GO
EXEC SP_ADDROLE 'KHACHHANG'

GRANT SELECT ON DOITAC TO KHACHHANG
go
GRANT SELECT ON TAIXE to KHACHHANG
GO
GRANT SELECT, INSERT, UPDATE ON DONHANG to KHACHHANG
go
GRANT SELECT ON THUCDON to KHACHHANG
go
GRANT SELECT ON MONAN to KHACHHANG
go
GRANT SELECT ON TUYCHON to KHACHHANG
go
GRANT SELECT,INSERT,UPDATE ON CT_DANHGIA to KHACHHANG
go
GRANT SELECT,INSERT,UPDATE ON CT_DONHANG to KHACHHANG
go

GRANT EXECUTE ON kh_xem_doi_tac_error to KHACHHANG
GRANT EXECUTE ON kh_xem_doi_tac to KHACHHANG
GRANT EXECUTE ON kh_xem_tt_tai_xe to KHACHHANG
GRANT EXECUTE ON kh_xem_ct_don_hang to KHACHHANG
GRANT EXECUTE ON kh_tao_don_hang to KHACHHANG
GRANT EXECUTE ON kh_huy_don_hang_error to KHACHHANG
GRANT EXECUTE ON kh_huy_don_hang to KHACHHANG


---- < Role: QUANTRI - QuanTri > ----
GO
EXEC SP_ADDROLE 'QUANTRI'

GRANT EXECUTE ON Cap_Quyen TO QUANTRI
GRANT EXECUTE ON SUA_TT_TX TO QUANTRI
GRANT EXECUTE ON COI_DON_HANG_TX TO QUANTRI
GRANT EXECUTE ON SUA_TTKV_TX TO QUANTRI
GRANT EXECUTE ON SUA_MK TO QUANTRI
GRANT EXECUTE ON Them_TK TO QUANTRI
GRANT EXECUTE ON Xoa_tk TO QUANTRI
GRANT EXECUTE ON Tao_user TO QUANTRI
GRANT EXECUTE ON Xoa_user TO QUANTRI
GRANT EXECUTE ON Cap_Quyen_Coi TO QUANTRI
GRANT EXECUTE ON Cap_Quyen_Them TO QUANTRI
GRANT EXECUTE ON Cap_Quyen_Xoa TO QUANTRI
GRANT EXECUTE ON Cap_Quyen_Exec TO QUANTRI


---- < Role: TAIXE > ----
GO
EXEC SP_ADDROLE 'TAIXE'

GRANT SELECT ON TAIXE TO TAIXE
GRANT SELECT, UPDATE ON TAIXE(HoTen, CCCD, SDT, DiaChi, BienSoXe, Email, STK_NH) TO TAIXE
GRANT SELECT ON DONHANG TO TAIXE
GRANT SELECT ON DOITAC(TenQuan, TP, Quan, Email, LoaiAmThuc, SDT, DiemDanhGiaDT) TO TAIXE
GRANT SELECT ON CUAHANG TO TAIXE
GRANT SELECT, UPDATE ON DONHANG(MaTaiXe, TinhTrang) TO TAIXE
GRANT SELECT, UPDATE ON KHUVUCHD(Phuong, Quan, TP) TO TAIXE
GRANT SELECT ON CT_DANHGIA TO TAIXE

GRANT EXECUTE ON TX_Xem_DS_DonHang TO TAIXE
GRANT EXECUTE ON Nhan_DonHang TO TAIXE
GRANT EXECUTE ON Xem_LS_GiaoHang TO TAIXE
GRANT EXECUTE ON Xem_CT_DanhGia_TX TO TAIXE


---- < Role: NHANVIEN > ----
GO
EXEC SP_ADDROLE 'NHANVIEN'
GRANT SELECT, INSERT ON HOPDONG TO NHANVIEN

GRANT EXECUTE ON Duyet_Hop_Dong TO NHANVIEN
GRANT EXECUTE ON Xem_DS_HopDong TO NHANVIEN